export const paths = {
  home: '/',
  auth: { signIn: '/auth/sign-in', signUp: '/auth/sign-up', resetPassword: '/auth/reset-password', jwt: { login: '/auth/jwt/login', register: '/auth/jwt/register' } },
  dashboard: {
    overview: '/dashboard',
    account: '/dashboard/account',
    integrations: '/dashboard/integrations',
    settings: '/dashboard/settings',
    user: '/dashboard/user',
    role: '/dashboard/role',
    userCreation: '/dashboard/userCreation',
    userEdit: (id: string) => `/dashboard/user/${id}`,
    team: '/dashboard/team',
    teamCreation: '/dashboard/teamCreation',
    teamEdit: (id: string) => `/dashboard/team/${id}`,
    customer: '/dashboard/customer',
    job: '/dashboard/job',
    expense: '/dashboard/expense',
    expenseDashboard: '/dashboard/expenseDashboard',
    expenseApproval: '/dashboard/expense/approval',
    expensePayment: '/dashboard/expense/payment',
  },
  errors: { notFound: '/errors/404' },
} as const;
